_base_: '../_base_/cityscapes_1024x1024.yml'

batch_size: 4
iters: 160000

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.005
  end_lr: 0
  power: 0.9
  warmup_iters: 1000
  warmup_start_lr: 1.0e-05

test_config:
  aug_eval: true
  scales: 1.0


loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000 
    - type: OhemCrossEntropyLoss
      min_kept: 130000 
    - type: OhemCrossEntropyLoss
      min_kept: 130000 
  coef: [10,1,3]

model:
  type: DSMONet_B
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
